# See FortifyVulnerabilityExporter documentation for FoD connection settings and release selection

export:
  from: fod
  to: json.gitlab.sast

fod:
  release:
    embed:                                          # Load static scan summary as required for GitLab output
      - propertyName: staticScanSummary
        uri: /api/v3/scans/{currentStaticScanId}/summary
        embedIf: currentStaticScanId!=null
  vulnerability:
    filterParam: scantype:Static                    # Have FoD return only static issues 
    embed:                                          # Also load details and recommendations as required for GitLab output
      - subEntity: details
      - subEntity: recommendations

export.dir: ${CI_PROJECT_DIR:${export.default.dir}} # Unless overridden, use CI_PROJECT_DIR if defined, otherwise default export dir
json.gitlab.sast.output:
  stdout: false                                     # Disabled by default to avoid vulnerability data being exposed through log files
  pretty: true                                      # Useful for debugging, disable for optimal performance
  file:   ${export.dir}/gl-fortify-sast.json        # Output file