# See FortifyVulnerabilityExporter documentation for FoD connection settings and release selection

export:
  from: fod
  to: csv

#fod:
#  vulnerability:
    # embed:                  # Load extra data, depending on what data you want to include in output
    #   - subEntity: details

export.dir: ${export.default.dir} # Use default export directory (unless overridden)
csv:
  output:
    stdout: false             # Disabled by default to avoid vulnerability data being exposed through log files
    file:   ${export.dir}/${release.applicationName}-${release.releaseName}.csv
  fields:
    source: Fortify on Demand
    scanType: $[vuln.scantype]
    id: $[vuln.id]
    issueInstanceId: $[vuln.instanceId]
    category: $[vuln.category]
    file: $[vuln.primaryLocationFull]
    line: $[vuln.lineNumber]