# See FortifyVulnerabilityExporter documentation for SSC connection settings and application version selection

export:
  from: ssc
  to: json.gitlab.sast, json.gitlab.dast, json.gitlab.sonatype, json.gitlab.debricked

ssc:
  version:
    embed:
      - subEntity: currentStaticScan
        onError: LOG_INFO
      - subEntity: currentDynamicScan
        onError: LOG_INFO
      - subEntity: currentSonatypeScan
        onError: LOG_INFO
  vulnerability:
    embed:                                             # Also load details as required for GitLab output
      - subEntity: details                                                 

export.dir: ${CI_PROJECT_DIR:${export.default.dir}}    # Unless overridden, use CI_PROJECT_DIR if defined, otherwise default export dir
json.gitlab.sast.output:
  stdout: false                                        # Disabled by default to avoid vulnerability data being exposed through log files
  pretty: true                                         # Useful for debugging, disable for optimal performance
  file:  ${export.dir}/gl-fortify-sast.json            # Output file
  
json.gitlab.dast.output:
  stdout: false                                        # Disabled by default to avoid vulnerability data being exposed through log files
  pretty: true                                         # Useful for debugging, disable for optimal performance
  file:   ${export.dir}/gl-fortify-dast.json           # Output file
  
json.gitlab.sonatype.output:
  stdout: false                                        # Disabled by default to avoid vulnerability data being exposed through log files
  pretty: true                                         # Useful for debugging, disable for optimal performance
  file:   ${export.dir}/gl-fortify-sonatype-depscan.json  # Output file

json.gitlab.debricked.output:
  stdout: false                                        # Disabled by default to avoid vulnerability data being exposed through log files
  pretty: true                                         # Useful for debugging, disable for optimal performance
  file:   ${export.dir}/gl-fortify-debricked-depscan.json # Output file